/** Define ids for each page. */
export const PAGE_IDS = {
  ABOUT_US: 'about-us',
  ADD_STUFF: 'add-stuff',
  ADD_EVENT: 'add-event',
  COMMUNITY_GROUPS: 'community-groups',
  CONTACT_US: 'contact-us',
  EDIT_EVENT: 'edit-event',
  EDIT_ORGANIZATION: 'edit-organization',
  EDIT_STUFF: 'edit-stuff',
  FAQ: 'faq',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_EVENTS: 'list-events',
  LIST_ORGANIZATIONS: 'list-organizations',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  MANAGE_DATABASE: 'manage-database',
  MY_ACCOUNT: 'my-account',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  REGISTER_ORGANIZATION: 'register-organization',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  VIEW_ORGANIZATION: 'view-organization',
};
