import React, { useState } from 'react';

const Dalle = () => {
  const [description, setDescription] = useState('');
  const [generatedImage, setGeneratedImage] = useState('');

  const handleGenerateImage = async () => {
    try {
      const response = await fetch('/api/generate-image', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: description }),
      });
      const data = await response.json();
      if (data && data.image) {
        setGeneratedImage(data.image);
      } else {
        console.error('Failed to generate image:', data);
        alert('Failed to generate image. Please try again.');
      }
    } catch (error) {
      console.error('Error generating image:', error);
      alert('An error occurred. Please try again.');
    }
  };

  return (
    <div>
      <h1>Generate Image with DALL·E</h1>
      <textarea
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        placeholder="Enter description here..."
        rows="4"
        cols="50"
      />
      <button onClick={handleGenerateImage}>Generate Image</button>
      {generatedImage && <img src={generatedImage} alt="Generated by DALL·E" />}
    </div>
  );
};

export default Dalle;
